# Generated by Django 3.2.6 on 2021-09-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20210921_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
