# Generated by Django 3.2.6 on 2021-09-27 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_alter_product_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
            ],
        ),
    ]
