# Generated by Django 3.2.6 on 2021-09-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_alter_product_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('True', 'Beli'), ('False', 'Xeyr')], default=True, max_length=10),
        ),
    ]
