# Generated by Django 3.2.6 on 2021-09-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Var', 'Beli'), ('Yox', 'Xeyr')], default=True, max_length=10),
        ),
    ]
