# Generated by Django 3.2.6 on 2021-10-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='newprice',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
