# Generated by Django 3.2.6 on 2021-10-05 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_product_newprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='newprice',
            new_name='oldprice',
        ),
    ]
