# Generated by Django 3.2.6 on 2021-09-02 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_contactform_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='ContactFormMessage',
        ),
    ]
