# Generated by Django 3.2.6 on 2021-09-28 11:39

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0023_alter_product_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20)),
                ('author', models.CharField(blank=True, max_length=150)),
                ('description', models.CharField(blank=True, max_length=20)),
                ('price', models.FloatField()),
                ('amount', models.IntegerField()),
                ('slug', models.SlugField(unique=True)),
                ('detail', ckeditor_uploader.fields.RichTextUploadingField()),
                ('status', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, upload_to='images/users/')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
