# Generated by Django 3.2.6 on 2021-09-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createproductmodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
