# Generated by Django 3.2.6 on 2021-09-28 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_alter_product_managers'),
        ('user', '0002_alter_createproductmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='createproductmodel',
            name='category',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='createproductmodel',
            name='image',
            field=models.ImageField(blank=True, default='uploads/images/indir.jpg', upload_to='images/'),
        ),
    ]
