# Generated by Django 3.2.6 on 2021-10-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210928_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createproductmodel',
            name='image',
            field=models.ImageField(blank=True, default='uploads/images/indir.jpg', upload_to='uploads/'),
        ),
    ]
