# Generated by Django 3.2.6 on 2021-09-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('xəbər', 'xəbər'), ('bildirim', 'bildirim'), ('endirim', 'endirim')], max_length=10),
        ),
    ]
